version: '3.9'

services:
  database:
    image: mongo
    container_name: user-crud-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: user-crud
    ports:
      - '27017:27017'
    volumes:
      - mongo-database:/data/db

  app:
    build: .
    container_name: user-crud
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  mongo-database:
    external: true
